package org.apache.flink.quickstart;

import org.apache.flink.api.java.tuple.Tuple;
import org.apache.flink.api.java.tuple.Tuple1;

/**
 * TestData is generated by TestDataGenerator, which is the custom data format to test Meter.
 *
 */
public class TestData implements DataSourceFormat {
    private final long timestamp;
    private final long value;
    private final long id;
    private static final int FIELD_NUM = 3;

    private TestData(long timestamp, int value, long id) {
        this.timestamp = timestamp;
        this.value = value;
        this.id = id;
    }

    public static DataSourceFormat fromString(String line) {
        String[] tokens = line.split(",");
        if (tokens.length != FIELD_NUM) {
            throw new RuntimeException("Invalid Record: " + line);
        }
        return new TestData(Long.parseLong(tokens[0]), Integer.parseInt(tokens[1]), Long.parseLong(tokens[2]));
    }

    @Override
    public String toString() {
        return "TestData{" +
                "timestamp=" + timestamp +
                ", value=" + value +
                ", id=" + id +
                '}';
    }

    @Override
    public long getEventTime() {
        return this.timestamp;
    }

    @Override
    public <T extends Tuple> T getKey() {
        return (T) new Tuple1<>(this.id);
    }


    @Override
    public long getValue() {
        return this.value;
    }
}
